;;;; kernel.lisp -- layer 2 builds layer 3: the Forth kernel image for the STM32F446.
;;;;
;;;; Indirect-threaded. r4 = IP, r5 = data stack pointer (full descending, holds the second
;;;; item), r6 = TOS, r7 = W (current xt), sp = return stack. NEXT: ldr r7,[r4],#4;
;;;; ldr r0,[r7]; bx r0. Header: link, flags (80 immediate, 40 hidden), length, name,
;;;; pad to 4, code field, body. Primitives are `defcode` templates (a name plus a Thumb-2
;;;; body, NEXT appended); the high-level kernel is metacompiled from kernel.fs.
;;;; Usage: sbcl --script kernel.lisp OUT.bin

(load (merge-pathnames "asm.lisp" *load-truename*))
(in-package :thumb)

;;; ---------- memory map ----------
(defconstant +sysvars+ #x20000000)        ; state base latest dp >in #tib hld nneg
(defconstant +tib+ #x20000040)            ; 512-byte input buffer
(defconstant +padend+ #x200002C0)         ; pictured numeric output grows down from here
(defconstant +ram-dict+ #x20000300)       ; first free RAM for the user dictionary
(defconstant +dstop+ #x2001EFE0)          ; data stack: 4 KiB below this
(defconstant +rstop+ #x2001FFE0)          ; return stack: 4 KiB below this (QEMU: keep off the last 32 bytes)
(defconstant +dict-limit+ #x2001DEE0)     ; dictionary stops 256 bytes above the data stack
(defconstant +usart2+ #x40004400)
(defparameter *sysvars* '("state" "base" "latest" "dp" ">in" "#tib" "hld" "nneg" "emit-hook"))

;;; ---------- dictionary ----------
(defvar *xts* (make-hash-table :test 'equal))
(defvar *defined* (make-hash-table :test 'equal))
(defvar *last-link* nil)
(defun xt (name) (or (gethash name *xts*) (setf (gethash name *xts*) (label))))
(defun byte8 (b) (sb-assem:emit-byte *seg* (ldb (byte 8 0) b)))

(defun header (name &optional (flags 0))
  "Lay down a header; return NAME's xt label, marked at the code field."
  (when (gethash name *defined*) (error "~a defined twice" name))
  (align4)
  (let ((link (mark (label))))
    (if *last-link* (abs32 *last-link*) (w32 0))
    (setf *last-link* link)
    (byte8 flags) (byte8 (length name))
    (loop for c across name do (byte8 (char-code c)))
    (align4)
    (setf (gethash name *defined*) t)
    (mark (xt name))))

(defvar *docol* (label)) (defvar *dovar* (label)) (defvar *docon* (label))
(defun next () (ldr :w :ip 4 :post) (ldr :r0 :w) (bx :r0))
(defun dpush (r) (str :tos :psp -4 :pre) (unless (eql r :tos) (mov :tos r)))
(defun dpop (r) (ldr r :psp 4 :post))

(defmacro defcode (name (&key (next t) (flags 0)) &body body)
  `(let ((code (label)))
     (header ,name ,flags)
     (abs32 code 1)
     (mark code)
     ,@body
     ,@(when next '((next)))))
(defun defconst (name value &optional (addend 0))
  "A constant: an integer, or a label's address plus ADDEND."
  (header name) (abs32 *docon* 1)
  (if (integerp value) (w32 value) (abs32 value addend)))

;;; ---------- primitives ----------
(defun binop (fn) (dpop :r0) (funcall fn :tos :r0 :tos))
(defun flag (c) "TOS = -1 if condition C, else 0 (flags already set)." (movw :tos 0) (it c) (mvn-0 :tos))
(defun cmp2 (c) (dpop :r0) (cmp-reg :r0 :tos) (flag c))
(defun cmp0 (c) (cmp-imm8 :tos 0) (flag c))
(defun store-or (addr value) (li :r1 addr) (ldr :r0 :r1) (li :r2 value) (orr-reg :r0 :r0 :r2) (str :r0 :r1))

(defun primitives ()
  (defcode "exit" () (pop1 :ip))
  (defcode "lit" () (dpush :tos) (ldr :tos :ip 4 :post))
  (defcode "branch" () (ldr :ip :ip))
  (defcode "0branch" () (mov :r0 :tos) (dpop :tos) (ldr :r1 :ip 4 :post) (cmp-imm8 :r0 0) (it :eq) (mov :ip :r1))
  (defcode "execute" (:next nil) (mov :w :tos) (dpop :tos) (ldr :r0 :w) (bx :r0))
  (defcode "(do)" () (ldr :r0 :ip 4 :post) (push1 :r0) (dpop :r1) (push1 :r1) (push1 :tos) (dpop :tos))
  (defcode "(?do)" ()
    (let ((go (label)) (done (label)))
      (ldr :r0 :ip 4 :post) (dpop :r1) (cmp-reg :r1 :tos) (bcc :ne go)
      (mov :ip :r0) (dpop :tos) (b done)
      (mark go) (push1 :r0) (push1 :r1) (push1 :tos) (dpop :tos)
      (mark done)))
  (defcode "(loop)" ()
    (let ((out (label)) (done (label)))
      (ldr :r0 :sp) (addw :r0 :r0 1) (ldr :r1 :sp 4) (cmp-reg :r0 :r1) (bcc :eq out)
      (str :r0 :sp) (ldr :ip :ip) (b done)
      (mark out) (addw :sp :sp 12) (addw :ip :ip 4)
      (mark done)))
  (defcode "(+loop)" ()
    (let ((out (label)) (done (label)))
      (ldr :r2 :sp) (ldr :r1 :sp 4) (sub-reg :r0 :r2 :r1) (add-reg :r3 :r0 :tos) (add-reg :r2 :r2 :tos)
      (dpop :tos) (eor-reg :r0 :r0 :r3) (cmp-imm8 :r0 0) (bcc :lt out)
      (str :r2 :sp) (ldr :ip :ip) (b done)
      (mark out) (addw :sp :sp 12) (addw :ip :ip 4)
      (mark done)))
  (defcode "i" () (dpush :tos) (ldr :tos :sp))
  (defcode "j" () (dpush :tos) (ldr :tos :sp 12))
  (defcode "unloop" () (addw :sp :sp 12))
  (defcode "leave" () (ldr :ip :sp 8) (addw :sp :sp 12))
  (defcode "(s\")" ()
    (ldrb :r0 :ip) (addw :r1 :ip 1) (str :tos :psp -4 :pre) (str :r1 :psp -4 :pre) (mov :tos :r0)
    (add-reg :ip :r1 :r0) (addw :ip :ip 3) (movw :r2 3) (bic-reg :ip :ip :r2))
  ;; stack
  (defcode "dup" () (dpush :tos))
  (defcode "drop" () (dpop :tos))
  (defcode "swap" () (ldr :r0 :psp) (str :tos :psp) (mov :tos :r0))
  (defcode "over" () (ldr :r0 :psp) (dpush :r0))
  (defcode "rot" () (ldr :r0 :psp) (ldr :r1 :psp 4) (str :r0 :psp 4) (str :tos :psp) (mov :tos :r1))
  (defcode "-rot" () (ldr :r0 :psp) (ldr :r1 :psp 4) (str :tos :psp 4) (str :r1 :psp) (mov :tos :r0))
  (defcode "nip" () (addw :psp :psp 4))
  (defcode "tuck" () (ldr :r0 :psp) (str :tos :psp) (str :r0 :psp -4 :pre))
  (defcode "pick" () (add-reg :r0 :psp :tos :lsl 2) (ldr :tos :r0))
  (defcode "?dup" () (cmp-imm8 :tos 0) (it :ne) (str :tos :psp -4 :pre))
  (defcode "2dup" () (ldr :r0 :psp) (str :tos :psp -4 :pre) (str :r0 :psp -4 :pre))
  (defcode "2drop" () (addw :psp :psp 4) (dpop :tos))
  (defcode ">r" () (push1 :tos) (dpop :tos))
  (defcode "r>" () (dpush :tos) (pop1 :tos))
  (defcode "r@" () (dpush :tos) (ldr :tos :sp))
  (defcode "rdrop" () (addw :sp :sp 4))
  (defcode "depth" () (li :r0 +dstop+) (sub-reg :r0 :r0 :psp) (mov-shift :r0 :r0 :asr 2) (dpush :r0))
  (defcode "sp@" () (dpush :tos) (mov :tos :psp))
  (defcode "sp!" () (addw :psp :tos 4) (ldr :tos :tos))
  (defcode "rp@" () (dpush :tos) (mov :tos :sp))
  (defcode "rp!" () (mov :sp :tos) (dpop :tos))
  ;; arithmetic and logic
  (defcode "+" () (binop #'add-reg))
  (defcode "-" () (binop #'sub-reg))
  (defcode "*" () (binop #'mul))
  (defcode "/" () (binop #'sdiv))
  (defcode "mod" () (dpop :r0) (sdiv :r1 :r0 :tos) (mls :tos :r1 :tos :r0))
  (defcode "/mod" () (ldr :r0 :psp) (sdiv :r1 :r0 :tos) (mls :r2 :r1 :tos :r0) (str :r2 :psp) (mov :tos :r1))
  (defcode "u/mod" () (ldr :r0 :psp) (udiv :r1 :r0 :tos) (mls :r2 :r1 :tos :r0) (str :r2 :psp) (mov :tos :r1))
  (defcode "m*" () (ldr :r0 :psp) (smull :r1 :r2 :r0 :tos) (str :r1 :psp) (mov :tos :r2))
  (defcode "um*" () (ldr :r0 :psp) (umull :r1 :r2 :r0 :tos) (str :r1 :psp) (mov :tos :r2))
  (defcode "negate" () (movw :r0 0) (sub-reg :tos :r0 :tos))
  (defcode "abs" () (mov-shift :r0 :tos :asr 31) (eor-reg :tos :tos :r0) (sub-reg :tos :tos :r0))
  (defcode "and" () (binop #'and-reg))
  (defcode "or" () (binop #'orr-reg))
  (defcode "xor" () (binop #'eor-reg))
  (defcode "bic" () (dpop :r0) (bic-reg :tos :r0 :tos))
  (defcode "invert" () (mvn-reg :tos :tos))
  (defcode "lshift" () (dpop :r0) (lsl-reg :tos :r0 :tos))
  (defcode "rshift" () (dpop :r0) (lsr-reg :tos :r0 :tos))
  (defcode "arshift" () (dpop :r0) (asr-reg :tos :r0 :tos))
  (defcode "1+" () (addw :tos :tos 1))
  (defcode "1-" () (subw :tos :tos 1))
  (defcode "2+" () (addw :tos :tos 2))
  (defcode "2-" () (subw :tos :tos 2))
  (defcode "2*" () (mov-shift :tos :tos :lsl 1))
  (defcode "2/" () (mov-shift :tos :tos :asr 1))
  (defcode "cells" () (mov-shift :tos :tos :lsl 2))
  (defcode "cell+" () (addw :tos :tos 4))
  (defcode "min" () (dpop :r0) (cmp-reg :r0 :tos) (it :lt) (mov :tos :r0))
  (defcode "max" () (dpop :r0) (cmp-reg :r0 :tos) (it :gt) (mov :tos :r0))
  (defcode "=" () (cmp2 :eq)) (defcode "<>" () (cmp2 :ne))
  (defcode "<" () (cmp2 :lt)) (defcode ">" () (cmp2 :gt))
  (defcode "<=" () (cmp2 :le)) (defcode ">=" () (cmp2 :ge))
  (defcode "u<" () (cmp2 :lo)) (defcode "u>" () (cmp2 :hi))
  (defcode "0=" () (cmp0 :eq)) (defcode "0<>" () (cmp0 :ne))
  (defcode "0<" () (cmp0 :lt)) (defcode "0>" () (cmp0 :gt))
  ;; memory
  (defcode "@" () (ldr :tos :tos))
  (defcode "!" () (dpop :r0) (str :r0 :tos) (dpop :tos))
  (defcode "c@" () (ldrb :tos :tos))
  (defcode "c!" () (dpop :r0) (strb :r0 :tos) (dpop :tos))
  (defcode "h@" () (ldrh :tos :tos))
  (defcode "h!" () (dpop :r0) (strh :r0 :tos) (dpop :tos))
  (defcode "+!" () (dpop :r0) (ldr :r1 :tos) (add-reg :r1 :r1 :r0) (str :r1 :tos) (dpop :tos))
  (defcode "bis!" () (dpop :r0) (ldr :r1 :tos) (orr-reg :r1 :r1 :r0) (str :r1 :tos) (dpop :tos))
  (defcode "bic!" () (dpop :r0) (ldr :r1 :tos) (bic-reg :r1 :r1 :r0) (str :r1 :tos) (dpop :tos))
  (defcode "cbis!" () (dpop :r0) (ldrb :r1 :tos) (orr-reg :r1 :r1 :r0) (strb :r1 :tos) (dpop :tos))
  (defcode "cbic!" () (dpop :r0) (ldrb :r1 :tos) (bic-reg :r1 :r1 :r0) (strb :r1 :tos) (dpop :tos))
  (defcode "move" ()                     ; ( src dst n ) overlap-safe
    (let ((back (label)) (fl (label)) (bl2 (label)) (done (label)))
      (mov :r2 :tos) (dpop :r1) (dpop :r0) (dpop :tos)
      (cmp-reg :r0 :r1) (bcc :lo back)
      (mark fl) (cmp-imm8 :r2 0) (bcc :eq done)
      (ldrb :r3 :r0 1 :post) (strb :r3 :r1 1 :post) (subw :r2 :r2 1) (b fl)
      (mark back) (add-reg :r0 :r0 :r2) (add-reg :r1 :r1 :r2)
      (mark bl2) (cmp-imm8 :r2 0) (bcc :eq done)
      (ldrb :r3 :r0 -1 :pre) (strb :r3 :r1 -1 :pre) (subw :r2 :r2 1) (b bl2)
      (mark done)))
  (defcode "fill" ()                     ; ( addr n c )
    (let ((lp (label)) (done (label)))
      (mov :r1 :tos) (dpop :r2) (dpop :r0) (dpop :tos)
      (mark lp) (cmp-imm8 :r2 0) (bcc :eq done)
      (strb :r1 :r0 1 :post) (subw :r2 :r2 1) (b lp)
      (mark done)))
  (defcode "compare" ()                  ; ( a1 n1 a2 n2 -- flag ) true if equal bytes
    (let ((lp (label)) (no (label)) (done (label)))
      (mov :r3 :tos) (dpop :r2) (dpop :r1) (dpop :r0) (movw :tos 0)
      (cmp-reg :r1 :r3) (bcc :ne done)
      (mark lp) (cmp-imm8 :r1 0) (bcc :eq no)
      (ldrb :r3 :r0 1 :post) (ldrb :r12 :r2 1 :post) (cmp-reg :r3 :r12) (bcc :ne done)
      (subw :r1 :r1 1) (b lp)
      (mark no) (mvn-0 :tos)
      (mark done)))
  (defcode "count" () (ldrb :r0 :tos 1 :post) (dpush :r0))
  ;; single-precision floats on the M4F FPU; a float is its IEEE-754 bit pattern in one cell
  (flet ((fbin (op) (dpop :r0) (vmov-s-r :s0 :r0) (vmov-s-r :s1 :tos) (funcall op :s0 :s0 :s1) (vmov-r-s :tos :s0))
         (fun (op) (vmov-s-r :s0 :tos) (funcall op :s0 :s0) (vmov-r-s :tos :s0))
         (fcmp (c) (dpop :r0) (vmov-s-r :s0 :r0) (vmov-s-r :s1 :tos) (vcmp :s0 :s1) (vmrs-apsr) (flag c)))
    (defcode "f+" () (fbin #'vadd))
    (defcode "f-" () (fbin #'vsub))
    (defcode "f*" () (fbin #'vmul))
    (defcode "f/" () (fbin #'vdiv))
    (defcode "s>f" () (fun #'vcvt-f32-s32))
    (defcode "f>s" () (fun #'vcvt-s32-f32))
    (defcode "fsqrt" () (fun #'vsqrt))
    (defcode "f<" () (fcmp :mi))
    (defcode "f=" () (fcmp :eq)))
  ;; console: USART2, polled
  (defcode "emit" ()                     ; emit-hook = 0: USART2; else execute the hook with c on the stack
    (let ((wait (label)) (hook (label)) (done (label)))
      (li :r1 (+ +sysvars+ 32)) (ldr :r1 :r1) (cmp-imm8 :r1 0) (bcc :ne hook)
      (li :r1 +usart2+) (movw :r2 #x80)
      (mark wait) (ldr :r0 :r1) (tst-reg :r0 :r2) (bcc :eq wait)
      (str :tos :r1 4) (dpop :tos) (b done)
      (mark hook) (mov :w :r1) (ldr :r0 :w) (bx :r0)
      (mark done)))
  (defcode "key" ()
    (let ((wait (label)))
      (li :r1 +usart2+) (movw :r2 #x20)
      (mark wait) (ldr :r0 :r1) (tst-reg :r0 :r2) (bcc :eq wait)
      (dpush :tos) (ldr :tos :r1 4) (movw :r2 255) (and-reg :tos :tos :r2)))
  (defcode "key?" () (li :r1 +usart2+) (ldr :r0 :r1) (movw :r2 #x20) (dpush :tos) (tst-reg :r0 :r2) (flag :ne)))

(defun runtime-code ()
  "Code fields shared by all colon words, variables and constants."
  (mark *docol*) (push1 :ip) (addw :ip :w 4) (next)
  (mark *dovar*) (dpush :tos) (addw :tos :w 4) (next)
  (mark *docon*) (dpush :tos) (ldr :tos :w 4) (next))

(defun reset-code (reset fault cold-thread)
  (mark reset)
  (store-or #xE000ED88 #x00F00000)         ; CPACR: enable the FPU (CP10, CP11)
  (store-or #x40023830 1)                  ; RCC AHB1ENR: GPIOA
  (store-or #x40023840 (ash 1 17))         ; RCC APB1ENR: USART2
  (store-or #x40020000 #xA0)               ; GPIOA MODER: PA2, PA3 alternate function
  (store-or #x40020020 #x7700)             ; GPIOA AFRL: AF7 = USART2
  (li :r1 (+ +usart2+ 8)) (movw :r0 #x8B) (str :r0 :r1)          ; BRR: 115200 baud at 16 MHz HSI
  (li :r1 (+ +usart2+ 12)) (movw :r0 #x200C) (str :r0 :r1)       ; CR1: UE TE RE
  (li :r1 +sysvars+) (movw :r0 0) (str :r0 :r1 0)                ; state
  (movw :r0 10) (str :r0 :r1 4)                                  ; base
  (li :r0 *last-link*) (str :r0 :r1 8)                           ; latest
  (li :r0 +ram-dict+) (str :r0 :r1 12)                           ; dp
  (movw :r0 0) (str :r0 :r1 32)                                  ; emit-hook: console
  (li :psp +dstop+) (movw :tos 0)
  (li :ip cold-thread) (next)
  (mark fault)                                                    ; print FAULT, then system reset
  (let ((msg (label)) (lp (label)) (wait (label)) (done (label)))
    (li :r3 msg) (li :r1 +usart2+) (movw :r2 #x80)
    (mark lp) (ldrb :r0 :r3 1 :post) (cmp-imm8 :r0 0) (bcc :eq done)
    (mark wait) (ldr :r12 :r1) (tst-reg :r12 :r2) (bcc :eq wait) (str :r0 :r1 4) (b lp)
    (mark done) (li :r0 #xE000ED0C) (li :r1 #x05FA0004) (str :r1 :r0) (b done)
    (mark msg) (loop for c across (format nil "~c~%FAULT: reset~%" #\Return) do (byte8 (char-code c))) (byte8 0)
    (align4)))

;;; ---------- metacompiler for kernel.fs ----------
(defun tokenize (text)
  "Whitespace tokens; \\ and ( ) comments dropped; the text after .\" s\" .( becomes (:string ...)."
  (let ((toks '()) (i 0) (n (length text)))
    (flet ((ws (c) (member c '(#\Space #\Tab #\Newline #\Return)))
           (upto (ch) (let ((e (or (position ch text :start i) n))) (prog1 (subseq text i e) (setf i (min n (1+ e)))))))
      (loop
        (loop while (and (< i n) (ws (char text i))) do (incf i))
        (when (>= i n) (return))
        (let* ((e (or (position-if #'ws text :start i) n)) (tok (subseq text i e)))
          (setf i e)
          (cond ((equal (first toks) ":") (push tok toks))     ; a name, even if it looks special
                ((string= tok "\\") (upto #\Newline))
                ((string= tok "(") (upto #\)))
                ((member tok '(".\"" "s\"") :test #'string=)
                 (incf i) (push tok toks) (push (list :string (upto #\")) toks))
                (t (push tok toks)))))
      (nreverse toks))))

(defun parse-num (tok)
  (let* ((neg (and (> (length tok) 1) (char= (char tok 0) #\-))) (s (if neg (subseq tok 1) tok))
         (base 10))
    (when (and (> (length s) 1) (char= (char s 0) #\$)) (setf base 16 s (subseq s 1)))
    (let ((v (ignore-errors (parse-integer s :radix base))))
      (and v (if neg (- v) v)))))

(defun cell (name) (abs32 (xt name)))
(defun lit (v) (cell "lit") (if (integerp v) (w32 v) (abs32 v)))

(defun compile-def (name body)
  "BODY: tokens between the name and ;. Control structures resolve to labels here."
  (let ((cs '()))
    (loop while body do
      (let ((tok (pop body)))
        (cond
          ((consp tok) (error "stray string in ~a" name))
          ((string= tok "if") (cell "0branch") (let ((l (label))) (abs32 l) (push l cs)))
          ((string= tok "else") (cell "branch") (let ((l (label))) (abs32 l) (mark (pop cs)) (push l cs)))
          ((string= tok "then") (mark (pop cs)))
          ((string= tok "begin") (push (mark (label)) cs))
          ((string= tok "until") (cell "0branch") (abs32 (pop cs)))
          ((string= tok "again") (cell "branch") (abs32 (pop cs)))
          ((string= tok "while") (cell "0branch") (let ((l (label)) (dest (pop cs))) (abs32 l) (push l cs) (push dest cs)))
          ((string= tok "repeat") (cell "branch") (abs32 (pop cs)) (mark (pop cs)))
          ((member tok '("do" "?do") :test #'string=)
           (cell (if (string= tok "do") "(do)" "(?do)"))
           (let ((leave (label))) (abs32 leave) (push leave cs) (push (mark (label)) cs)))
          ((member tok '("loop" "+loop") :test #'string=)
           (cell (if (string= tok "loop") "(loop)" "(+loop)")) (abs32 (pop cs)) (mark (pop cs)))
          ((string= tok "recurse") (cell name))
          ((string= tok "[']") (lit (xt (pop body))))
          ((string= tok "[char]") (lit (char-code (char (pop body) 0))))
          ((member tok '(".\"" "s\"") :test #'string=)
           (let ((s (second (pop body))))
             (cell "(s\")") (byte8 (length s)) (loop for c across s do (byte8 (char-code c))) (align4)
             (when (string= tok ".\"") (cell "type"))))
          ((parse-num tok) (lit (parse-num tok)))
          (t (cell tok)))))
    (when cs (error "unbalanced control structure in ~a" name))
    (cell "exit")))

(defun metacompile (path)
  (let ((toks (with-open-file (s path) (let ((str (make-string (file-length s)))) (tokenize (subseq str 0 (read-sequence str s)))))))
    (loop while toks do
      (let ((tok (pop toks)))
        (unless (equal tok ":") (error "kernel.fs: expected : at ~s" tok))
        (let* ((name (pop toks)) (end (position ";" toks :test #'equal)) (body (subseq toks 0 end))
               (imm (equal (nth (1+ end) toks) "immediate")))
          (setf toks (nthcdr (+ end (if imm 2 1)) toks))
          (header name (if imm #x80 0))
          (abs32 *docol* 1)
          (compile-def name body))))))

;;; ---------- image ----------
(defun build (out)
  (new-segment)
  (let ((reset (label)) (fault (label)) (cold-thread (label)))
    (w32 +rstop+) (abs32 reset 1)
    (dotimes (i 14) (abs32 fault 1))
    (runtime-code)
    (primitives)
    (loop for name in *sysvars* for i from 0 do (defconst name (+ +sysvars+ (* 4 i))))
    (defconst "tib" +tib+) (defconst "padend" +padend+) (defconst "sp0" (- +dstop+ 4))
    (defconst "rp0" +rstop+) (defconst "dict-limit" +dict-limit+)
    (defconst "docol" *docol* 1) (defconst "dovar" *dovar* 1) (defconst "docon" *docon* 1)
    (metacompile (merge-pathnames "kernel.fs" *load-truename*))
    (align4) (mark cold-thread) (cell "cold")
    (reset-code reset fault cold-thread))
  (let ((undefined (loop for k being the hash-keys of *xts* unless (gethash k *defined*) collect k)))
    (when undefined (error "undefined words: ~{~a~^ ~}" undefined)))
  (let ((bytes (segment-bytes)))
    (with-open-file (s out :direction :output :if-exists :supersede :element-type '(unsigned-byte 8))
      (write-sequence bytes s))
    (format t "kernel image: ~d bytes, ~d words~%" (length bytes) (hash-table-count *defined*))))

(build (or (second sb-ext:*posix-argv*) "kernel.bin"))